### PR TITLE
Community Links and Burger Menu

### PR DESCRIPTION
**Pull request by JelaniThompson**
Hey guys, this is just my implementation of the design changes that were suggested over in #24. If you had any suggestions for changes to the barf-worthy font and menu sidebar colour (that I based off my Slack sidebar) / styling in general to something that looks a lot better it would be much appreciated haha.

image

image

image

### CODE REVIEW

**Comment by JelaniThompson** [comment]
Once you're done providing some suggestions I can go ahead and switch over the styles to glamorous (if we're keeping that format).

**Comment by alex-wilmer** [comment]
Thanks for the PR! I'll get back to you asap. Regarding styles.. I was thinking of going the styled-components direction since it seems to be the most popular solution out now. Any thoughts on that subject?

**Comment by tazsingh** [comment]
@alex-wilmer Styled Components are amazing! But would recommend v2 as it has many many improvements including server side rendering. Not fully released yet but still usable.

**Comment by mihok** [comment]
@alex-wilmer Is the failed travis-ci check something we need to care about atm?

**Comment by teesloane** [comment]
@JelaniThompson Can you make the sidebar black instead of red? This is a personal request - I think that it might be a bit less red-heavy. Say a sidebar that is hard black with an opacity of somewhere between `0.5` and `0.8` ? 

The designer in me is being picky. Hope you don't mind.

**Comment by alex-wilmer** [comment]
@mihok not yet. once we think the PR is good to merge, if tests are still not passing a simple `eslint --fix` should suffice, unless flow catches some type errors and we can address those separately. 

will add some commands to make this process easier for anyone.

@teesloane I like the idea of black / dark grey background. not so crazy about transparency though. if there's something noticeable coming through the transparency it would make the links slightly harder to read.

@JelaniThompson I have a few more comments as well I'll write them up soon. sorry for the delay

**Comment by teesloane** [comment]
@alex-wilmer good point. 0.9 + a blur?!  ;)

**Comment by JelaniThompson** [comment]
Hey @teesloane! Just tried out your suggestion. It looks a lot better than what I had in mind 😄 

image

**Pull request closed without merging**
