### PR TITLE
fixing an ally issue and getting some linting things

### PR DESCRIPTION
**Pull request by MandyMeindersma**
Okay so your linting things are a little weird to me. Have you recently introduced a linter but not all files have gone through it? Cause I have to make a lot of changes to make the linter pass. 

I really only wanted to add a alt text for ally lol

### CODE REVIEW

**Review by kieran — APPROVED** [review]
Wow, that linter is annoying!

thanks for adding the alt text!

**Comment by MandyMeindersma** [comment]
I also was having issues with the old events page. It wasn't recognizing splash so I just commented it out

**Comment by kieran** [comment]
Yeah, I figured. I think that entire for is due for deletion. We should do a group programming session where we recompose this repo.

you’re good to merge in the meantime!

**Comment by MandyMeindersma** [comment]
I don't have the permissions to do that I think ahah

**Comment by kieran** [comment]
can't figure out to allow that while still requiring reviews - merging now

**Comment by usrrname** [comment]
Thanks for your contribution @MandyMeindersma!  It was indeed very old, and this site hadnt been updated since 2017/19 and our old friend buds have gone on to do other cool things. 

Previously I noticed one always had to use the `git commit -m 'your message' --no-verify` flag to force-commit... I tried to make the smallest upgrade from React 15-> 16, I hope kieran's rewrite in coffeescript with parcel makes it easier

**Pull request merged**
